services:
  - type: web
    name: FindAccommodation
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python accommodationSearchApp/manage.py collectstatic --noinput
    startCommand: cd accommodationSearchApp && gunicorn accommodationSearchApp.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        value: "django-insecure-83fly(by7c4z()nq*&ris453kd*f3+1#o8n_e50=k=ei7u+7&&"
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: findaccommodation.onrender.com
      - key: DISABLE_COLLECTSTATIC
        value: 1 