# Generated by Django 5.1.7 on 2025-06-04 09:31

import autoslug.fields
import ckeditor.fields
import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('LANDLORD', 'Landlord'), ('TENANT', 'Tenant')], max_length=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='username', unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tiện nghi, tiện ích',
                'verbose_name_plural': 'Tiện nghi, tiện ích',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('citizen_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='landlord_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Chủ nhà trọ',
                'verbose_name_plural': 'Chủ nhà trọ',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accommodationSearch.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motel',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motel_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('total_rooms', models.IntegerField()),
                ('available_rooms', models.IntegerField()),
                ('rating_score', models.FloatField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhà trọ',
                'verbose_name_plural': 'Nhà trọ',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='MotelImage',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_type', models.CharField(choices=[('INSIDE', 'Inside'), ('OUTSIDE', 'Outside')], max_length=20)),
                ('motel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodationSearch.motel')),
            ],
            options={
                'verbose_name': 'hình ảnh',
                'verbose_name_plural': 'Hình ảnh nhà trọ',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('NEW_POST', 'New Post'), ('NEW_COMMENT', 'New Comment'), ('NEW_MOTEL', 'New Motel'), ('COMMENT_LIKE', 'Comment Like'), ('VERIFICATION_SUCCESS', 'Verification Success'), ('MOTEL_UPDATE', 'Motel Update'), ('MOTEL_LIKE', 'Motel Like'), ('FOLLOW', 'Follow'), ('PAYMENT', 'Payment'), ('SYSTEM', 'System')], max_length=20)),
                ('related_object_id', models.CharField(blank=True, max_length=36, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('RENT_OUT', 'Rent Out'), ('FIND_ROOM', 'Find Room')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('slug_source', models.CharField(default='title', max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('desired_address', models.TextField(blank=True, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('radius_km', models.FloatField(blank=True, null=True)),
                ('desired_latitude', models.FloatField(blank=True, null=True)),
                ('desired_longitude', models.FloatField(blank=True, null=True)),
                ('motel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accommodationSearch.motel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Bài Post',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accommodationSearch.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodationSearch.post')),
            ],
            options={
                'verbose_name': 'Bình Luận',
                'verbose_name_plural': 'Bình luận',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_type', models.CharField(choices=[('INSIDE', 'Inside'), ('OUTSIDE', 'Outside')], default='INSIDE', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodationSearch.post')),
            ],
            options={
                'verbose_name': 'Hình ảnh bài đăng',
                'verbose_name_plural': 'Hình ảnh bài đăng',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('area', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_people', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('amenities', models.ManyToManyField(to='accommodationSearch.amenity')),
                ('motel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accommodationSearch.motel')),
            ],
            options={
                'verbose_name': 'Phòng trọ',
                'verbose_name_plural': 'Phòng trọ',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('VNPAY', 'Vnpay'), ('STRIPE', 'Stripe'), ('CASH', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('vnp_transaction_no', models.CharField(blank=True, max_length=15, null=True)),
                ('vnp_bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('vnp_bank_tran_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vnp_card_type', models.CharField(blank=True, max_length=20, null=True)),
                ('vnp_pay_date', models.DateTimeField(blank=True, null=True)),
                ('vnp_response_code', models.CharField(blank=True, max_length=2, null=True)),
                ('vnp_txn_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_payments', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_payments', to='accommodationSearch.room')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodationSearch.room')),
            ],
            options={
                'verbose_name': 'hình ảnh',
                'verbose_name_plural': 'Hình ảnh phòng trọ',
            },
        ),
        migrations.CreateModel(
            name='RoomTenant',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_entries', to='accommodationSearch.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search_params', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử tìm kiếm',
                'verbose_name_plural': 'Lịch sử tìm kiếm',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('citizen_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tenant_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(related_name='roomer', through='accommodationSearch.RoomTenant', to='accommodationSearch.room')),
            ],
            options={
                'verbose_name': 'Người thuê trọ',
                'verbose_name_plural': 'Người thuê trọ',
            },
        ),
        migrations.AddField(
            model_name='roomtenant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_entries', to='accommodationSearch.tenant'),
        ),
        migrations.AddField(
            model_name='room',
            name='tenants',
            field=models.ManyToManyField(related_name='rented_rooms', through='accommodationSearch.RoomTenant', to='accommodationSearch.tenant'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_message_time', models.DateTimeField(auto_now_add=True)),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Theo dõi',
                'verbose_name_plural': 'Theo dõi',
                'unique_together': {('followed_user', 'follower_user')},
            },
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodationSearch.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like bình luận',
                'verbose_name_plural': 'Like bình luận',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='LikeMotel',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('motel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodationSearch.motel')),
            ],
            options={
                'verbose_name': 'Like nhà trọ',
                'verbose_name_plural': 'Like nhà trọ',
                'unique_together': {('user', 'motel')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('motel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='accommodationSearch.motel')),
            ],
            options={
                'verbose_name': 'Yêu thích',
                'verbose_name_plural': 'Yêu thích',
                'unique_together': {('user', 'motel')},
            },
        ),
        migrations.CreateModel(
            name='MotelRating',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('motel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motel_ratings', to='accommodationSearch.motel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'unique_together': {('motel', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_name', 'motel')},
        ),
    ]
