# Generated by Django 5.1.7 on 2025-03-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='acvtive',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='acvtive',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='last_message_Time',
            new_name='last_message_time',
        ),
        migrations.RenameField(
            model_name='landlord',
            old_name='acvtive',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='likecomment',
            old_name='acvtive',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='likemotel',
            old_name='acvtive',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='motel',
            old_name='acvtive',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='is_Read',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='acvtive',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='realtimechat',
            old_name='Chatroom',
            new_name='chatroom',
        ),
        migrations.RenameField(
            model_name='realtimechat',
            old_name='senser',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='acvtive',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='acvtive',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='related_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followed')},
        ),
    ]
