# Generated by Django 5.1.7 on 2025-03-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0002_rename_acvtive_admin_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
