# Generated by Django 5.1.7 on 2025-03-26 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tenants',
            field=models.ManyToManyField(related_name='rented_rooms', through='accommodationSearch.RoomTenant', to='accommodationSearch.tenant'),
        ),
        migrations.AlterField(
            model_name='roomtenant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_entries', to='accommodationSearch.room'),
        ),
        migrations.AlterField(
            model_name='roomtenant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_entries', to='accommodationSearch.tenant'),
        ),
    ]
