# Generated by Django 5.1.7 on 2025-03-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0004_room_tenants_alter_roomtenant_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='landlord',
            options={'verbose_name': 'Chủ nhà trọ', 'verbose_name_plural': 'Danh sách chủ trọ'},
        ),
        migrations.AlterModelOptions(
            name='motel',
            options={'verbose_name': 'Nhà trọ', 'verbose_name_plural': 'Danh sách nhà trọ'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Người thuê trọ', 'verbose_name_plural': 'Danh sách người thuê trọ'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(to='accommodationSearch.amenity'),
        ),
    ]
