# Generated by Django 5.1.7 on 2025-03-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0005_amenity_alter_landlord_options_alter_motel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'tiện nghi, tiện ích', 'verbose_name_plural': 'Danh sách các tiện ích'},
        ),
        migrations.AlterField(
            model_name='motelimage',
            name='motel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodationSearch.motel'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodationSearch.room'),
        ),
    ]
