# Generated by Django 5.1.7 on 2025-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0006_alter_amenity_options_alter_motelimage_motel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
