# Generated by Django 5.1.7 on 2025-03-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0007_motel_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
