# Generated by Django 5.1.7 on 2025-03-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0008_room_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motelimage',
            options={'verbose_name': 'hình ảnh', 'verbose_name_plural': 'hình ảnh nhà trọ'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Thanh toán', 'verbose_name_plural': 'Danh sách thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Phòng trọ', 'verbose_name_plural': 'Danh sách phòng trọ'},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'hình ảnh', 'verbose_name_plural': 'hình ảnh phòng trọ'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
