# Generated by Django 5.1.7 on 2025-03-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0011_alter_motelimage_options_alter_roomimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Danh sách User'},
        ),
    ]
