# Generated by Django 5.1.7 on 2025-03-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0012_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='email',
        ),
    ]
