# Generated by Django 5.1.7 on 2025-03-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0013_remove_landlord_email_remove_tenant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='avatar',
            field=models.ImageField(null=True, upload_to='landlord/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='avatar',
            field=models.ImageField(null=True, upload_to='tenant/%Y/%m/'),
        ),
    ]
