# Generated by Django 5.1.7 on 2025-03-28 15:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0014_alter_landlord_avatar_alter_tenant_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
