# Generated by Django 5.1.7 on 2025-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0017_alter_comment_id_alter_follow_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='rooms',
            field=models.ManyToManyField(related_name='roomer', through='accommodationSearch.RoomTenant', to='accommodationSearch.room'),
        ),
    ]
