# Generated by Django 5.1.7 on 2025-03-31 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0018_tenant_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Bình Luận', 'verbose_name_plural': 'Danh sách bình luận'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Yêu thích', 'verbose_name_plural': 'Danh sách yêu thích'},
        ),
        migrations.AlterModelOptions(
            name='motelrating',
            options={'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Danh sách đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Danh sách bài Post'},
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='following',
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'motel')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('following', 'followers')},
        ),
    ]
