# Generated by Django 5.1.7 on 2025-03-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0019_alter_comment_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Tiện nghi, tiện ích', 'verbose_name_plural': 'Tiện nghi, tiện ích'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Bình Luận', 'verbose_name_plural': 'Bình luận'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Yêu thích', 'verbose_name_plural': 'Yêu thích'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Theo dõi', 'verbose_name_plural': 'Theo dõi'},
        ),
        migrations.AlterModelOptions(
            name='landlord',
            options={'verbose_name': 'Chủ nhà trọ', 'verbose_name_plural': 'Chủ nhà trọ'},
        ),
        migrations.AlterModelOptions(
            name='likecomment',
            options={'verbose_name': 'Like bình luận', 'verbose_name_plural': 'Like bình luận'},
        ),
        migrations.AlterModelOptions(
            name='likemotel',
            options={'verbose_name': 'Like nhà trọ', 'verbose_name_plural': 'Like nhà trọ'},
        ),
        migrations.AlterModelOptions(
            name='motel',
            options={'verbose_name': 'Nhà trọ', 'verbose_name_plural': 'Nhà trọ'},
        ),
        migrations.AlterModelOptions(
            name='motelimage',
            options={'verbose_name': 'hình ảnh', 'verbose_name_plural': 'Hình ảnh nhà trọ'},
        ),
        migrations.AlterModelOptions(
            name='motelrating',
            options={'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name': 'Thông báo', 'verbose_name_plural': 'Thông báo'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Thanh toán', 'verbose_name_plural': 'Thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Bài Post'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Phòng trọ', 'verbose_name_plural': 'Phòng trọ'},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'hình ảnh', 'verbose_name_plural': 'Hình ảnh phòng trọ'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name': 'Lịch sử tìm kiếm', 'verbose_name_plural': 'Lịch sử tìm kiếm'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Người thuê trọ', 'verbose_name_plural': 'Người thuê trọ'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
    ]
