# Generated by Django 5.1.7 on 2025-03-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0021_alter_amenity_id_alter_chatroom_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motel',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='motel',
            name='province',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
