# Generated by Django 5.1.7 on 2025-03-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0022_alter_motel_district_alter_motel_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motel',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='motel',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
