# Generated by Django 5.1.7 on 2025-04-02 07:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0025_remove_user_date_joined_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='full_name', unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='room_name', unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='full_name', unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='username', unique=True),
        ),
    ]
