# Generated by Django 5.1.7 on 2025-04-02 13:10

import autoslug.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0026_amenity_slug_landlord_slug_post_slug_room_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='motel',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=autoslug.fields.AutoSlugField(null=True, unique=True),
        ),
    ]
