# Generated by Django 5.1.7 on 2025-04-02 14:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0027_amenity_active_user_date_joined_alter_amenity_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True),
        ),
        migrations.AlterField(
            model_name='motel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='slug_source', unique=True),
        ),
    ]
