# Generated by Django 5.1.7 on 2025-04-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0030_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motelimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motelrating',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='realtimechat',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
