# Generated by Django 5.1.7 on 2025-04-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0032_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
