# Generated by Django 5.1.7 on 2025-04-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0033_alter_notifications_related_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_source',
            field=models.CharField(default='title', max_length=255),
        ),
    ]
