# Generated by Django 5.1.7 on 2025-04-30 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0034_post_slug_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motelrating',
            name='tenant',
        ),
        migrations.AddField(
            model_name='motelrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
