# Generated by Django 5.1.7 on 2025-04-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0035_remove_motelrating_tenant_motelrating_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='motelrating',
            unique_together={('motel', 'user')},
        ),
    ]
