# Generated by Django 5.1.7 on 2025-05-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0036_alter_motelrating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vnp_bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vnp_bank_tran_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vnp_card_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vnp_pay_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vnp_response_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vnp_transaction_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vnp_txn_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
