# Generated by Django 5.1.7 on 2025-05-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0039_follow_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtenant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
