# Generated by Django 5.1.7 on 2025-05-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0040_favorite_active_roomtenant_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='avatar',
        ),
    ]
