# Generated by Django 5.1.7 on 2025-05-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0041_remove_landlord_avatar_remove_tenant_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='followed_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='follower_user',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('followed_user', 'follower_user')},
        ),
    ]
