# Generated by Django 5.1.7 on 2025-05-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0042_rename_followers_follow_followed_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motel',
            options={'ordering': ['-created_date'], 'verbose_name': 'Nhà trọ', 'verbose_name_plural': 'Nhà trọ'},
        ),
    ]
