# Generated by Django 5.1.7 on 2025-05-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0044_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='landlord_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
