# Generated by Django 5.1.7 on 2025-05-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0045_alter_landlord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('NEW_POST', 'New Post'), ('NEW_COMMENT', 'New Comment'), ('COMMENT_LIKE', 'Comment Like'), ('ACCOUNT_VERIFICATION', 'Account Verification'), ('MOTEL_UPDATE', 'Motel Update'), ('MOTEL_LIKE', 'Motel Like'), ('FOLLOW', 'Follow'), ('PAYMENT', 'Payment'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
