# Generated by Django 5.1.7 on 2025-05-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0046_alter_notifications_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('NEW_POST', 'New Post'), ('NEW_COMMENT', 'New Comment'), ('NEW_MOTEL', 'New Motel'), ('COMMENT_LIKE', 'Comment Like'), ('VERIFICATION_SUCCESS', 'Verification Success'), ('MOTEL_UPDATE', 'Motel Update'), ('MOTEL_LIKE', 'Motel Like'), ('FOLLOW', 'Follow'), ('PAYMENT', 'Payment'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
