# Generated by Django 5.1.7 on 2025-05-25 08:10

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0047_alter_notifications_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_type', models.CharField(choices=[('INSIDE', 'Inside'), ('OUTSIDE', 'Outside')], default='INSIDE', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodationSearch.post')),
            ],
            options={
                'verbose_name': 'Hình ảnh bài đăng',
                'verbose_name_plural': 'Hình ảnh bài đăng',
                'ordering': ['order'],
            },
        ),
    ]
