# Generated by Django 5.1.7 on 2025-05-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0049_alter_payment_payer_alter_payment_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm_token',
        ),
    ]
