# Generated by Django 5.1.7 on 2025-06-01 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodationSearch', '0050_remove_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motelrating',
            name='motel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motel_ratings', to='accommodationSearch.motel'),
        ),
        migrations.AlterField(
            model_name='motelrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
