server {
    listen 80;
    server_name systemaccommodation.online www.systemaccommodation.online;

    # Redirect toàn bộ HTTP sang HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name systemaccommodation.online www.systemaccommodation.online;

    ssl_certificate /etc/letsencrypt/live/systemaccommodation.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/systemaccommodation.online/privkey.pem;

    location /static/ {
        alias /static/;
    }

    location / {
        proxy_pass http://django:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
