const dataListCate = [
    {
        id: '1',
        name: 'Phòng trọ Bình Tân',
        location: '4/x Miếu Bình Đông, P. Bình Hưng Hoà A, Q. Bình Tân',
        price: '2.8 triệu',
        image: require('../assets/images/meomeo1.jpg'),
        details: 'Còn 1 phòng trống',
        total: 'Tổng: 4 phòng',
    },
    {
        id: '2',
        name: 'Phòng trọ Tân Phú',
        location: 'Nguyễn Hữu Dật, P. Tây Thạnh, Q. Tân Phú',
        price: '3.0 triệu',
        image: require('../assets/images/meomeo1.jpg'),
        details: 'Còn 2 phòng trống',
        total: 'Tổng: 5 phòng',
    },
    {
        id: '3',
        name: 'Phòng trọ Bình Chiểu',
        location: 'Đường số 2 kp6, P. Bình Chiểu, TP. Thủ Đức',
        price: '1.8 - 2.4 triệu',
        image: require('../assets/images/meomeo1.jpg'),
        details: 'Còn 2 phòng trống',
        total: 'Tổng: 3 phòng',
    },
    {
        id: '4',
        name: 'Phòng trọ Tân Bình',
        location: 'Trần Thánh Tông, P.15, Q. Tân Bình',
        price: '3.0 triệu',
        image: require('../assets/images/meomeo1.jpg'),
        details: 'Còn 1 phòng trống',
        total: 'Tổng: 2 phòng',
    },
    {
        id: '5',
        name: 'Phòng trọ Gò Vấp',
        location: 'Lê Đức Thọ, P.15, Q. Gò Vấp',
        price: '2.5 triệu',
        image: require('../assets/images/meomeo1.jpg'),
        details: 'Còn 3 phòng trống',
        total: 'Tổng: 6 phòng',
    },
    {
        id: '6',
        name: 'Phòng trọ Phú Nhuận',
        location: 'Phan Đăng Lưu, P.5, Q. Phú Nhuận',
        price: '4.0 triệu',
        image: require('../assets/images/meomeo1.jpg'),
        details: 'Còn 1 phòng trống',
        total: 'Tổng: 3 phòng',
    },
    {
        id: '7',
        name: 'Phòng trọ Quận 10',
        location: 'CMT8, P.12, Q.10',
        price: '3.2 triệu',
        image: require('../assets/images/meomeo1.jpg'),
        details: 'Còn 2 phòng trống',
        total: 'Tổng: 4 phòng',
    },
    {
        id: '8',
        name: 'Phòng trọ Thủ Đức',
        location: 'Võ Văn Ngân, P. Linh Chiểu, TP. Thủ Đức',
        price: '2.7 triệu',
        image: require('../assets/images/meomeo1.jpg'),
        details: 'Còn 1 phòng trống',
        total: 'Tổng: 2 phòng',
    },
];

export default dataListCate;